In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import os
import mmcv
import importlib
import torch
import torchvision.transforms as transforms
from mmcv import Config
from mmcls.datasets.pipelines import Compose
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.gridspec as gridspec
from PIL import Image
import heapq
from mmseg.apis import inference_segmentor, init_segmentor
from mmseg.core.evaluation import get_palette
from pytorch_grad_cam.utils.image import show_cam_on_image
import cv2

import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    

from scripts import generate_statistics_single
from scripts import visualization_seg_masks
from scripts import generate_statistics
from scripts import generate_cams
from scripts import utils
from scripts.utils.pipeline import get_pipeline_torchvision
from scripts import generate_segs
from scripts import visualize_cam_results

In [2]:
configSeg = '../segmentation/ocrnet_hr48_512x512_carparts_noflip/ocrnet_hr48_512x512_carparts_noflip.py'
checkpointSeg = '../segmentation/ocrnet_hr48_512x512_carparts_noflip/latest.pth'
imgRootTrain = '../data/CompCars_sv_original_split/train'
imgRootVal = '../data/CompCars_sv_original_split/val'
configCAMResOG = '../CAMModels/resnet/compCars_Original/resnet50_b128x2_compcars-original-split.py'
checkpointCAMResOG = '../CAMModels/resnet/compCars_Original/latest.pth'
configCAMSwinSmallOG = '../CAMModels/swinSmall/compCars_Original/swin-small_b128x2_compcars-original-split.py'
checkpointCAMSwinSmallOG = '../CAMModels/swinSmall/compCars_Original/latest.pth'
annfileTrain = '../annfileTrain.txt'
annfileVal = '../annfileVal.txt'
annfileValGt = '../annfileValGt.txt'
imgNameTrain='Acura_Acura_ILX_2a6cce617fc27d.jpg'
imgNameVal = 'Acura_Acura_ILX_3c11ef9e42931b.jpg'
imgPathTrain=os.path.join(imgRootTrain, imgNameTrain)
imgPathVal=os.path.join(imgRootVal, imgNameVal)

paletteName='Comp_Original_Ocrnet_Carparts_Noflip'

segDataPath = 'G:/XAI-Vehicle-Classification/preGenData/Segmentations/CompCars_Original/valAllSegs.npz'

camDataGradCAM = 'G:/XAI-Vehicle-Classification/preGenData/preGenData/CompCars_original/ResNet/valAllCAMs.npz'
camDataEigenCAM = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsEigen.npz'
camDataEigenGrad = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsEigenGrad.npz'
camDataGradCAMGPU = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsGPU.npz'
camDataGradCAMPlusPlus = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsGrad++.npz'
camDataLayerCAM = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsLayer.npz'
camDataXCAM = 'G:/XAI-Vehicle-Classification/preGenData/CompCars_original/ResNet/valAllCAMsXGrad.npz'

In [76]:
res, labels, dataset, gt = generate_statistics.generate_statistics_missclassified(imgRoot=imgRootVal, camConfig=configCAMResOG, 
                                                       camCheckpoint=checkpointCAMResOG, camData=camDataGradCAM,
                                                       segData=segDataPath, dataClasses=['Acura_Acura_ILX'],
                                                       annfile=annfileValGt)

Created filtered annotation file at ..\annfile_filtered.txt
{'type': 'CompCars', 'data_prefix': '../data/CompCars_sv_original_split/val', 'ann_file': '..\\annfile_filtered.txt', 'pipeline': [{'type': 'LoadImageFromFile'}, {'type': 'Resize', 'size': (256, -1)}, {'type': 'CenterCrop', 'crop_size': 224}, {'type': 'Normalize', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'to_rgb': True}, {'type': 'ImageToTensor', 'keys': ['img']}, {'type': 'Collect', 'keys': ['img']}]}
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3/3, 0.5 task/s, elapsed: 6s, ETA:     0sCreating annotation file at ..\annfile_correct.txt
Creating annotation file at ..\annfile_incorrect.txt


In [33]:
labels

array([0, 0, 0], dtype=int64)

In [34]:
gt

array([0, 0, 0], dtype=int64)

In [38]:
labels & gt

array([0, 0, 0], dtype=int64)

In [45]:
labels == np.array([2,0,1])

array([False,  True, False])

In [43]:
np.array([0,0,1]) == np.array([1,0,0])

array([False,  True, False])

In [50]:
np.array(dataset.data_infos)[labels==gt]

array([{'img_prefix': '../data/CompCars_sv_original_split/val', 'img_info': {'filename': 'Acura_Acura_ILX_3c11ef9e42931b.jpg'}, 'gt_label': array(0, dtype=int64)},
       {'img_prefix': '../data/CompCars_sv_original_split/val', 'img_info': {'filename': 'Acura_Acura_ILX_3f182088df7c66.jpg'}, 'gt_label': array(0, dtype=int64)},
       {'img_prefix': '../data/CompCars_sv_original_split/val', 'img_info': {'filename': 'Acura_Acura_ILX_7ec5dcfce68270.jpg'}, 'gt_label': array(0, dtype=int64)}],
      dtype=object)

In [52]:
np.array(dataset.data_infos)[labels==np.array([2,0,1])]

array([{'img_prefix': '../data/CompCars_sv_original_split/val', 'img_info': {'filename': 'Acura_Acura_ILX_3f182088df7c66.jpg'}, 'gt_label': array(0, dtype=int64)}],
      dtype=object)

In [68]:
[match['img_info']['filename'] + " " + str(match['gt_label'].item()) + "_0" for match in np.array(dataset.data_infos)[labels==gt]]

['Acura_Acura_ILX_3c11ef9e42931b.jpg 0_0',
 'Acura_Acura_ILX_3f182088df7c66.jpg 0_0',
 'Acura_Acura_ILX_7ec5dcfce68270.jpg 0_0']

In [75]:
[match['img_info']['filename'] + " " + str(match['gt_label'].item()) + "_0" for match in np.array(dataset.data_infos)[np.logical_not(labels==np.array([2,0,1]))]]

['Acura_Acura_ILX_3c11ef9e42931b.jpg 0_0',
 'Acura_Acura_ILX_7ec5dcfce68270.jpg 0_0']