In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import os
import mmcv
import torch
from mmcv import Config
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.gridspec as gridspec

In [2]:
configCAM = '../CAMModels/resnet/compCars_Original/resnet50_b128x2_compcars-original-split.py'
cfg = Config.fromfile(configCAM)

In [4]:
cfg.data.test

{'type': 'CompCars',
 'data_prefix': 'data/CompCars_sv_original_split/val',
 'ann_file': 'data/CompCars_sv_original_split/meta/val.txt',
 'pipeline': [{'type': 'LoadImageFromFile'},
  {'type': 'Resize', 'size': (256, -1)},
  {'type': 'CenterCrop', 'crop_size': 224},
  {'type': 'Normalize',
   'mean': [123.675, 116.28, 103.53],
   'std': [58.395, 57.12, 57.375],
   'to_rgb': True},
  {'type': 'ImageToTensor', 'keys': ['img']},
  {'type': 'Collect', 'keys': ['img']}]}

In [4]:
def t(**kwargs):
    print(kwargs)
    
def g(test=None,F=None):
    print(test)
    print(F)
    
def h(**kwargs):
    g(kwargs)

In [2]:
t(test='test')

{'test': 'test'}


In [5]:
h(test='test')

{'test': 'test'}
None


In [9]:
a = np.random.randint(0,10,(1,2,4))

In [10]:
a

array([[[4, 8, 4, 7],
        [8, 8, 6, 2]]])

In [11]:
a.mean(axis=1).mean(axis=0)

array([6. , 8. , 5. , 4.5])

In [12]:
a.mean(axis=0)

array([[4., 8., 4., 7.],
       [8., 8., 6., 2.]])

In [13]:
a.mean(axis=1)

array([[6. , 8. , 5. , 4.5]])